import type { RouteComponent } from 'vue-router'

export const views: Record<
  PageRoute.LastDegreeRouteKey,
  RouteComponent | (() => Promise<{ default: RouteComponent }>)
> = {
  '403': () => import('@/views/_builtin/403/index.vue'),
  '404': () => import('@/views/_builtin/404/index.vue'),
  '500': () => import('@/views/_builtin/500/index.vue'),
  'not-found': () => import('@/views/_builtin/not-found/index.vue'),
  'constant-page': () => import('@/views/_builtin/constant-page/index.vue'),
  'login': () => import('@/views/_builtin/login/index.vue'),
  'about': () => import('@/views/about/index.vue'),
  // 'auth-demo_permission': () => import('@/views/auth-demo/permission/index.vue'),
  // 'auth-demo_super': () => import('@/views/auth-demo/super/index.vue'),
  // 'component_button': () => import('@/views/component/button/index.vue'),
  // 'component_card': () => import('@/views/component/card/index.vue'),
  // 'component_table': () => import('@/views/component/table/index.vue'),
  // 'dashboard_analysis': () => import('@/views/dashboard/analysis/index.vue'),
  // 'dashboard_workbench': () => import('@/views/dashboard/workbench/index.vue'),
  // 'document_naive': () => import('@/views/document/naive/index.vue'),
  // 'document_project-link': () => import('@/views/document/project-link/index.vue'),
  // 'document_project': () => import('@/views/document/project/index.vue'),
  // 'document_vite': () => import('@/views/document/vite/index.vue'),
  // 'document_vue': () => import('@/views/document/vue/index.vue'),
  // 'exception_403': () => import('@/views/exception/403/index.vue'),
  // 'exception_404': () => import('@/views/exception/404/index.vue'),
  // 'exception_500': () => import('@/views/exception/500/index.vue'),
  // 'function_tab-detail': () => import('@/views/function/tab-detail/index.vue'),
  // 'function_tab-multi-detail': () => import('@/views/function/tab-multi-detail/index.vue'),
  // 'function_tab': () => import('@/views/function/tab/index.vue'),
  // 'function_websocket': () => import('@/views/function/websocket/index.vue'),
  // 'management_auth': () => import('@/views/management/auth/index.vue'),
  // 'management_role': () => import('@/views/management/role/index.vue'),
  // 'management_route': () => import('@/views/management/route/index.vue'),
  // 'management_user': () => import('@/views/management/user/index.vue'),
  // 'multi-menu_first_second-new_third': () => import('@/views/multi-menu/first/second-new/third/index.vue'),
  // 'multi-menu_first_second': () => import('@/views/multi-menu/first/second/index.vue'),
  // 'plugin_charts_antv': () => import('@/views/plugin/charts/antv/index.vue'),
  // 'plugin_charts_echarts': () => import('@/views/plugin/charts/echarts/index.vue'),
  // 'plugin_copy': () => import('@/views/plugin/copy/index.vue'),
  // 'plugin_editor_markdown': () => import('@/views/plugin/editor/markdown/index.vue'),
  // 'plugin_editor_quill': () => import('@/views/plugin/editor/quill/index.vue'),
  // 'plugin_icon': () => import('@/views/plugin/icon/index.vue'),
  // 'plugin_map': () => import('@/views/plugin/map/index.vue'),
  // 'plugin_print': () => import('@/views/plugin/print/index.vue'),
  // 'plugin_swiper': () => import('@/views/plugin/swiper/index.vue'),
  // 'plugin_video': () => import('@/views/plugin/video/index.vue'),
}
